In [1]:
from src import functions
from src import my_functions
import pytest
import cartopy

import warnings

In [2]:
functions.foo_function(4)

16

In [1]:
! pytest

============================= test session starts ==============================
platform linux -- Python 3.9.7, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/jupyter-u6079899/EMSC-4033-2022-assignment-Group3/Lucas
plugins: anyio-3.5.0
collected 6 items                                                              

tests/test_functions.py .....F                                           [100%]

=================================== FAILURES ===================================
____________________ test_my_global_raster_data_lats_longs _____________________

    def test_my_global_raster_data_lats_longs():
        """Tests if the first two columns of the output of my_global_raster_data contain acceptible latitude and longitude values and are not equal to 0."""
    
        all_raster_data = my_global_raster_data()
        test_data = all_raster_data[1]
    
        #other people may have these in a different order to me
        #so I just check that the first two columns contain latitudes and 

In [4]:
type(my_functions.my_earth_features()[0])



cartopy.feature.NaturalEarthFeature

In [9]:
?pytest.warns


Signature:
pytest.warns(
    *args: Any,
    match: Union[str, Pattern[str], NoneType] = None,
    **kwargs: Any,
) -> Union[ForwardRef('WarningsChecker'), Any]
Docstring:
Assert that code raises a particular class of warning.

Specifically, the parameter ``expected_warning`` can be a warning class or
sequence of warning classes, and the inside the ``with`` block must issue a warning of that class or
classes.

This helper produces a list of :class:`warnings.WarningMessage` objects,
one for each warning raised.

This function can be used as a context manager, or any of the other ways
:func:`pytest.raises` can be used::

    >>> import pytest
    >>> with pytest.warns(RuntimeWarning):
    ...    warnings.warn("my warning", RuntimeWarning)

In the context manager form you may use the keyword argument ``match`` to assert
that the warning matches a text or regex::

    >>> with pytest.warns(UserWarning, match='must be 0 or None'):
    ...     warnings.warn("value must be 0 or None", UserWar

In [6]:
print(type(my_functions.my_basemaps().popitem()[1])== cartopy.io.img_tiles.OSM )


True


In [7]:
x = [0,2,3]
all(1<= y <= 5 for y in x)

False

In [8]:
?all

Signature: all(iterable, /)
Docstring:
Return True if bool(x) is True for all values x in the iterable.

If the iterable is empty, return True.
Type:      builtin_function_or_method


In [3]:
a = my_functions.my_global_raster_data()


Cloudstore connection established
Remote and local file size both 21.99 MB, skipping - global_age_data.3.6.z.npz


In [7]:
print(len(a))


1801


In [4]:
print(a[1])

[[-180.         89.9        55.370914]
 [-179.9        89.9        55.371075]
 [-179.8        89.9        55.361431]
 ...
 [ 179.8        89.9        55.363701]
 [ 179.9        89.9        55.363701]
 [ 180.         89.9        55.3643  ]]


In [8]:
all(x == 0 for x in a[1][:,0])

False

In [10]:
not(all(x == 0 for x in a[1][:,1]))

True

In [4]:
    all_raster_data = my_functions.my_global_raster_data()
    test_data = all_raster_data[1]

Cloudstore connection established
Remote and local file size both 21.99 MB, skipping - global_age_data.3.6.z.npz


In [5]:
test_data

array([[-180.      ,   89.9     ,   55.370914],
       [-179.9     ,   89.9     ,   55.371075],
       [-179.8     ,   89.9     ,   55.361431],
       ...,
       [ 179.8     ,   89.9     ,   55.363701],
       [ 179.9     ,   89.9     ,   55.363701],
       [ 180.      ,   89.9     ,   55.3643  ]])

In [6]:
    test3 = not(all(x == 0 for x in test_data[:,0]))
    test4 = not(all(x == 0 for x in test_data[:,1]))

In [7]:
test3

True

In [8]:
test4

True