In [20]:
from obspy.core import event
from obspy.clients.fdsn import Client
from obspy import UTCDateTime
import numpy as np

client = Client("IRIS")

?client.get_events
#?np.zeros

Signature:
client.get_events(
    starttime=None,
    endtime=None,
    minlatitude=None,
    maxlatitude=None,
    minlongitude=None,
    maxlongitude=None,
    latitude=None,
    longitude=None,
    minradius=None,
    maxradius=None,
    mindepth=None,
    maxdepth=None,
    minmagnitude=None,
    maxmagnitude=None,
    magnitudetype=None,
    eventtype=None,
    includeallorigins=None,
    includeallmagnitudes=None,
    includearrivals=None,
    eventid=None,
    limit=None,
    offset=None,
    orderby=None,
    catalog=None,
    contributor=None,
    updatedafter=None,
    filename=None,
    **kwargs,
)
Docstring:
Query the event service of the client.

>>> client = Client("IRIS")
>>> cat = client.get_events(eventid=609301)
>>> print(cat)
1 Event(s) in Catalog:
1997-10-14T09:53:11.070000Z | -22.145, -176.720 | 7.8 ...

The return value is a :class:`~obspy.core.event.Catalog` object
which can contain any number of events.

>>> t1 = UTCDateTime("2001-01-07T00:00:00")
>>> t2 = UTCDa

In [16]:
print(np.zeros((6,4)))



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
get_events()?


SyntaxError: invalid syntax (2012227654.py, line 1)

In [7]:
help(.get_events)


SyntaxError: invalid syntax (889474525.py, line 1)

In [1]:
?enumerate


Init signature: enumerate(iterable, start=0)
Docstring:     
Return an enumerate object.

  iterable
    an object supporting iteration

The enumerate object yields pairs containing a count (from start, which
defaults to zero) and a value yielded by the iterable argument.

enumerate is useful for obtaining an indexed list:
    (0, seq[0]), (1, seq[1]), (2, seq[2]), ...
Type:           type
Subclasses:     


In [5]:
for x in enumerate([1,2,"4",4]):
    print(x)

(0, 1)
(1, 2)
(2, '4')
(3, 4)
